### ISSUE TITLE
Blank page after connecting a wallet

### ISSUE THREAD

**Issue by avibaritone** [NearDeFi/burrow-cash#315]
After connecting a wallet (both NEAR and Sender) I'm redirected to https://app.burrow.cash/#/deposit which shows only a blank page. Refreshing the page changes nothing. Tested on recent Chrome, Safari and Firefox. 

There is an interesting log in the console:
```
TypeError: Cannot read properties of undefined (reading 'toLocaleString')
    at $c036515f367a8fa2$var$Reward (rewards.tsx:90:20)
    at pc (react-dom.production.min.js:157:137)
    at ti (react-dom.production.min.js:267:460)
    at Ni (react-dom.production.min.js:250:347)
    at ji (react-dom.production.min.js:250:278)
    at Pi (react-dom.production.min.js:250:138)
    at Ei (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at m (scheduler.production.min.js:18:343)
    at Xn (react-dom.production.min.js:122:325)
h$ @ react-dom.production.min.js:216
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'toLocaleString')
    at $c036515f367a8fa2$var$RewardGridRow (rewards.tsx:172:22)
    at pc (react-dom.production.min.js:157:137)
    at ti (react-dom.production.min.js:267:460)
    at Ni (react-dom.production.min.js:250:347)
    at ji (react-dom.production.min.js:250:278)
    at Pi (react-dom.production.min.js:250:138)
    at Ei (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at m (scheduler.production.min.js:18:343)
    at Xn (react-dom.production.min.js:122:325)
h$ @ react-dom.production.min.js:216
rewards.tsx:90 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLocaleString')
    at $c036515f367a8fa2$var$Reward (rewards.tsx:90:20)
    at pc (react-dom.production.min.js:157:137)
    at ti (react-dom.production.min.js:267:460)
    at Ni (react-dom.production.min.js:250:347)
    at ji (react-dom.production.min.js:250:278)
    at Pi (react-dom.production.min.js:250:138)
    at Ei (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at m (scheduler.production.min.js:18:343)
    at Xn (react-dom.production.min.js:122:325)
```

**Comment by avibaritone** [comment]
Seems to be fixed in https://github.com/NearDeFi/burrow-cash/commit/09839554d41350d9bba69e9ad9101daa512aa459, thanks!
